name: Build RustDesk Windows MSI

on:
  workflow_dispatch:

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "6f29f12e82a8293156836ad81cc9bf5af41fe836"

jobs:
  build-msi:
    runs-on: windows-2022

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 🛠️ Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: "1.81"
          targets: x86_64-pc-windows-msvc
          components: "rustfmt"

      - name: 🚀 Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: windows-2022

      - name: ⚙️ Setup vcpkg with Github Actions binary cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: 📦 Install vcpkg dependencies
        env:
          VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
        run: |
          if (!($env:VCPKG_ROOT\vcpkg install --triplet x64-windows-static --x-install-root="$env:VCPKG_ROOT\installed")) {
            Get-ChildItem -Path "$env:VCPKG_ROOT" -Filter "*.log" -Recurse | ForEach-Object {
              Write-Host "$($_.FullName):"
              Write-Host "======"
              Get-Content $_.FullName
              Write-Host "======"
              Write-Host ""
            }
            exit 1
          }
          Get-Content -Head 100 "$env:VCPKG_ROOT\buildtrees\ffmpeg\build-x64-windows-static-rel-out.log" -ErrorAction SilentlyContinue
        shell: powershell

      - name: 🔨 Build RustDesk
        run: |
          python3 .\build.py --portable --hwcodec --flutter --vram --skip-portable-pack
          mv .\flutter\build\windows\x64\runner\Release .\rustdesk

      - name: 📦 Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: 🏗️ Build MSI
        run: |
          pushd .\res\msi
          python preprocess.py --arp -d ../../rustdesk
          nuget restore msi.sln
          msbuild msi.sln -p:Configuration=Release -p:Platform=x64 /p:TargetVersion=Windows10
          popd

      - name: 📤 Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-msi
          path: res/msi/Package/bin/x64/Release/en-us/Package.msi
